src/Entity/Agence.php
<?php

namespace App\Entity;

use App\Repository\AgenceRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AgenceRepository::class)
 */
class Agence
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $telegence;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse_ville;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getTelegence(): ?string
    {
        return $this->telegence;
    }

    public function setTelegence(string $telegence): self
    {
        $this->telegence = $telegence;

        return $this;
    }

    public function getAdresseVille(): ?string
    {
        return $this->adresse_ville;
    }

    public function setAdresseVille(string $adresse_ville): self
    {
        $this->adresse_ville = $adresse_ville;

        return $this;
    }
}

src/Form/AgenceType.php
<?php

namespace App\Form;

use App\Entity\Agence;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AgenceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('telegence')
            ->add('adresse_ville')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Agence::class,
        ]);
    }
}

src/Controller/AgenceController.php
<?php

namespace App\Controller;

use App\Entity\Agence;
use App\Form\AgenceType;
use App\Repository\AgenceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/agence")
 */
class AgenceController extends AbstractController
{
    /**
     * @Route("/", name="agence_index", methods={"GET"})
     */
    public function index(AgenceRepository $agenceRepository): Response
    {
        return $this->render('agence/index.html.twig', [
            'agences' => $agenceRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="agence_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $agence = new Agence();
        $form = $this->createForm(AgenceType::class, $agence);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($agence);
            $entityManager->flush();

            return $this->redirectToRoute('agence_index');
        }

        return $this->render('agence/new.html.twig', [
            'agence' => $agence,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="agence_show", methods={"GET"})
     */
    public function show(Agence $agence): Response
    {
        return $this->render('agence/show.html.twig', [
            'agence' => $agence,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="agence_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Agence $agence): Response
    {
        $form = $this->createForm(AgenceType::class, $agence);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('agence_index');
        }

        return $this->render('agence/edit.html.twig', [
            'agence' => $agence,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="agence_delete", methods={"POST"})
     */
    public function delete(Request $request, Agence $agence): Response
    {
        if ($this->isCsrfTokenValid('delete'.$agence->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($agence);
            $entityManager->flush();
        }

        return $this->redirectToRoute('agence_index');
    }
}

templates/agence/_delete_form.html.twig
<form method="post" action="{{ path('agence_delete', {'id': agence.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ agence.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/agence/_form.html.twig
{{ form_start(form) }}
    <div class="mb-3">
        <label for="nom" class="form-label">{{ form_label(form.nom) }}</label>
        {{form_widget(form.nom, {'attr': {'class': 'form-control'}}) }} 
    </div>

    <div class="mb-3">
        <label for="telegence" class="form-label">{{ form_label(form.telegence) }}</label>
        {{form_widget(form.telegence, {'attr': {'class': 'form-control'}}) }} 
    </div>

    <div class="mb-3">
        <label class="form-check-label" for="adresse_ville">{{ form_label(form.adresse_ville) }}</label>
        {{ form_widget(form.adresse_ville, {'attr': {'class': 'form-control'}}) }}     
    </div>


    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/agence/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Agence{% endblock %}

{% block body %}
    <h1>Edit Agence</h1>

    {{ include('agence/_form.html.twig', {'button_label': 'Update'}) }}
    <div class="d-flex mt-2">
    <a href="{{ path('agence_index') }}" class="btn btn-info mx-2">back to list</a>

    {{ include('agence/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/agence/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Agence index{% endblock %}

{% block body %}
 
    <h2 class="my-5 text-light bg-dark ">Listes des Agences</h2>
    <table class="table table-dark table-striped table-hover">
        <thead>
            <tr>
                <th>#Id</th>
                <th>Nom</th>
                <th>Telegence</th>
                <th>Adresse_ville</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for agence in agences %}
            <tr>
                <td>{{ agence.id }}</td>
                <td>{{ agence.nom }}</td>
                <td>{{ agence.telegence }}</td>
                <td>{{ agence.adresseVille }}</td>
                <td class="d-flex">
                    <a href="{{ path('agence_show', {'id': agence.id}) }}" class="btn btn-primary">show</a>
                    <a href="{{ path('agence_edit', {'id': agence.id}) }}" class="btn btn-info">edit</a>
                    {{ include('agence/_delete_form.html.twig') }}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('agence_new') }}" class="btn btn-success">Ajouter une Agence</a>
{% endblock %}

templates/agence/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Agence{% endblock %}

{% block body %}
    <h1>Create new Agence</h1>

    {{ include('agence/_form.html.twig') }}

    <a href="{{ path('agence_index') }}">back to list</a>
{% endblock %}

templates/agence/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Agence{% endblock %}

{% block body %}
    <h1>Agence</h1>

    <table class="table table-dark table-striped table-hover">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ agence.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ agence.nom }}</td>
            </tr>
            <tr>
                <th>Telegence</th>
                <td>{{ agence.telegence }}</td>
            </tr>
            <tr>
                <th>Adresse_ville</th>
                <td>{{ agence.adresseVille }}</td>
            </tr>
        </tbody>
    </table>
    <div class="d-flex mt-2">
    <a href="{{ path('agence_index') }}" class="btn btn-primary">back to list</a>

        <a href="{{ path('agence_edit', {'id': agence.id}) }}" class="btn btn-info mx-5">edit</a>

        {{ include('agence/_delete_form.html.twig') }}
    </div>
  
{% endblock %}