src/Entity/Voiture.php
<?php

namespace App\Entity;

use App\Repository\VoitureRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=VoitureRepository::class)
 */
class Voiture
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $Marque;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $couleur;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $nb_place;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_agence;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMarque(): ?string
    {
        return $this->Marque;
    }

    public function setMarque(string $Marque): self
    {
        $this->Marque = $Marque;

        return $this;
    }

    public function getCouleur(): ?string
    {
        return $this->couleur;
    }

    public function setCouleur(string $couleur): self
    {
        $this->couleur = $couleur;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getNbPlace(): ?int
    {
        return $this->nb_place;
    }

    public function setNbPlace(int $nb_place): self
    {
        $this->nb_place = $nb_place;

        return $this;
    }

    public function getNomAgence(): ?string
    {
        return $this->nom_agence;
    }

    public function setNomAgence(string $nom_agence): self
    {
        $this->nom_agence = $nom_agence;

        return $this;
    }
}

src/Form/VoitureType.php
<?php

namespace App\Form;

use App\Entity\Voiture;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VoitureType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Marque')
            ->add('couleur')
            ->add('description')
            ->add('nb_place')
            ->add('nom_agence')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Voiture::class,
        ]);
    }
}

src/Controller/VoitureController.php
<?php

namespace App\Controller;

use App\Entity\Voiture;
use App\Form\VoitureType;
use App\Repository\VoitureRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/voiture")
 */
class VoitureController extends AbstractController
{
    /**
     * @Route("/", name="voiture_index", methods={"GET"})
     */
    public function index(VoitureRepository $voitureRepository): Response
    {
        return $this->render('voiture/index.html.twig', [
            'voitures' => $voitureRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="voiture_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $voiture = new Voiture();
        $form = $this->createForm(VoitureType::class, $voiture);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($voiture);
            $entityManager->flush();

            return $this->redirectToRoute('voiture_index');
        }

        return $this->render('voiture/new.html.twig', [
            'voiture' => $voiture,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="voiture_show", methods={"GET"})
     */
    public function show(Voiture $voiture): Response
    {
        return $this->render('voiture/show.html.twig', [
            'voiture' => $voiture,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="voiture_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Voiture $voiture): Response
    {
        $form = $this->createForm(VoitureType::class, $voiture);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('voiture_index');
        }

        return $this->render('voiture/edit.html.twig', [
            'voiture' => $voiture,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="voiture_delete", methods={"POST"})
     */
    public function delete(Request $request, Voiture $voiture): Response
    {
        if ($this->isCsrfTokenValid('delete'.$voiture->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($voiture);
            $entityManager->flush();
        }

        return $this->redirectToRoute('voiture_index');
    }
}

templates/voiture/_delete_form.html.twig
<form method="post" action="{{ path('voiture_delete', {'id': voiture.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ voiture.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/voiture/_form.html.twig
{{ form_start(form) }}
    

    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">{{ form_label(form.Marque) }}s</label>
        {{form_widget(form.Marque, {'attr': {'class': 'form-control'}}) }} 
    </div>

    <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">{{ form_label(form.couleur) }}</label>
        {{form_widget(form.couleur, {'attr': {'class': 'form-control'}}) }} 
    </div>

    <div class="mb-3">
        <label class="form-check-label" for="exampleCheck1">{{ form_label(form.description) }}</label>
        {{ form_widget(form.description, {'attr': {'class': 'form-control'}}) }}     
    </div>

    <div class="mb-3">
   
        <label class="form-check-label" for="exampleCheck1">{{ form_label(form.nb_place) }}</label>
        {{ form_widget(form.nb_place, {'attr': {'class': 'form-control'}}) }} 
    </div>

    <div class="mb-3">
        <label class="form-check-label" for="exampleCheck1">{{ form_label(form.nom_agence) }}</label>
       {{form_widget(form.nom_agence, {'attr': {'class': 'form-control'}}) }} 
    </div>

    <button class="btn btn-success">
     {{ button_label| default('Save') }}
    </button>
{{ form_end(form) }}

templates/voiture/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Voiture{% endblock %}

{% block body %}
    <h1>Edit Voiture</h1>

    {{ include('voiture/_form.html.twig', {'button_label': 'Update'}) }}
    <div class="d-flex mt-5">
    <a href="{{ path('voiture_index') }}" class="btn btn-info mx-2">back to list</a>
    {{ include('voiture/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/voiture/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Voiture index{% endblock %}

{% block body %}
    <h2 class="my-5 text-dark bg-light" >Listes des Voitures</h2>
    <table class="table table-light table-striped table-hover">
        <thead>
            <tr>
                <th scope="col">#ID</th>
                <th scope="col">Marque</th>
                <th scope="col">Couleur</th>
                <th scope="col">Description</th>
                <th scope="col">Nb_place</th>
                <th scope="col">Nom_agence</th>
                <th scope="col">actions</th>
            </tr>
        </thead>
        <tbody>
        {% for voiture in voitures %}
            <tr>
                <td>#{{ voiture.id }}</td>
                <td>{{ voiture.Marque }}</td>
                <td>{{ voiture.couleur }}</td>
                <td>{{ voiture.description }}</td>
                <td>{{ voiture.nbPlace }}</td>
                <td>{{ voiture.nomAgence }}</td>
                <td class="d-flex">
                    <a href="{{ path('voiture_show', {'id': voiture.id}) }}" class="btn btn-primary">show</a>
                    <a href="{{ path('voiture_edit', {'id': voiture.id}) }}" class="btn btn-dark">edit</a>
                    {{ include('voiture/_delete_form.html.twig') }}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('voiture_new') }}" class="btn btn-success">Ajouter une Voiture</a>
{% endblock %}

templates/voiture/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Voiture{% endblock %}

{% block body %}
    <h1>Create new Voiture</h1>

    {{ include('voiture/_form.html.twig') }}

    <a href="{{ path('voiture_index') }}">back to list</a>
{% endblock %}

templates/voiture/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Voiture{% endblock %}

{% block body %}
    <h1>Voiture</h1>

    <table class="table table-light table-striped table-hover">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ voiture.id }}</td>
            </tr>
            <tr>
                <th>Marque</th>
                <td>{{ voiture.Marque }}</td>
            </tr>
            <tr>
                <th>Couleur</th>
                <td>{{ voiture.couleur }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ voiture.description }}</td>
            </tr>
            <tr>
                <th>Nb_place</th>
                <td>{{ voiture.nbPlace }}</td>
            </tr>
            <tr>
                <th>Nom_agence</th>
                <td>{{ voiture.nomAgence }}</td>
            </tr>
        </tbody>
    </table>
    <div class="d-flex">
        <a href="{{ path('voiture_index') }}" class="btn btn-primary">back to list</a>

        <a href="{{ path('voiture_edit', {'id': voiture.id}) }}" class="btn btn-info mx-5">edit</a>

        {{ include('voiture/_delete_form.html.twig') }}
    <div>
{% endblock %}